modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Tamaized/FinalKobold/issues"
license="All Rights Reserved"
[[mods]]
modId="fk"
version="${version}"
displayName="FinalKobold"
credits=""
authors="Tamaized"
description='''

'''

[[dependencies.fk]]
    modId="twilightforest"
    mandatory=true
    versionRange="[4.1.1220,)"
    ordering="AFTER"
    side="BOTH"